spring.application.name=backend
#spring.security.user.name=user
#spring.security.user.password=pass
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_BEHAVIOR:create-drop}

# disables the hot rebuild/reload provided by spring dev tools
# spring.devtools.restart.enabled=false