spring.application.name=harmony-backend

# Environment
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}

server.port=${PORT:8080}

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false

# Frontend
frontEndBaseUrl=${FRONT_END_BASE_URL}

# Security
spring.security.oauth2.client.registration.discord.client-id=${DISCORD_CLIENT_ID}
spring.security.oauth2.client.registration.discord.client-secret=${DISCORD_CLIENT_SECRET}
spring.security.oauth2.client.registration.discord.scope=identify,email
spring.security.oauth2.client.registration.discord.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.discord.redirect-uri={baseUrl}/login/oauth2/code/discord
spring.security.oauth2.client.provider.discord.authorization-uri=https://discord.com/api/oauth2/authorize
spring.security.oauth2.client.provider.discord.token-uri=https://discord.com/api/oauth2/token
spring.security.oauth2.client.provider.discord.user-info-uri=https://discord.com/api/users/@me
spring.security.oauth2.client.provider.discord.user-name-attribute=id
jwt.secret=${JWT_SECRET}

# Database config
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${validate}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# controls the hot reload provided by spring dev tools
spring.devtools.restart.enabled=${HOT_RELOAD:false}
spring.devtools.livereload.enabled=${HOT_RELOAD:false}

# Sentry
sentry.enabled=${SENTRY_ENABLED:false}
sentry.environment=${SENTRY_ENV:dev}
sentry.dsn=${SENTRY_DSN:}
# Sets Sentry to capture 10% of transactions for tracing.
sentry.traces-sample-rate=${SENTRY_SAMPLE_RATE:0.1}
# Determines whether to capture data like request headers, body and IP for users
sentry.send-default-pii=${SENTRY_PII_ENABLED:false}
sentry.max-request-body-size=none


#logging.level.org.springframework.security=TRACE