spring.application.name=backend
#spring.security.user.name=user
#spring.security.user.password=pass
spring.datasource.url=jdbc:postgresql://localhost:5432/harmony
spring.datasource.username=harmony_app
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
# TODO: change the 'ddl-auto' above to one of the following: <create | create-drop | update | validate | none>
#       Currently it makes it so that the DB is dropped on each app launch
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# disables the hot rebuild/reload provided by spring dev tools
# spring.devtools.restart.enabled=false