/*
    [Describe your changes here]
 */

---

CREATE TABLE [your_table_name_here] (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Use the line below for uuid instead of id
    -- uuid GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY

    -- for connecting to a user, you may want to connect to a diff table
    user_id UUID NOT NULL,
    CONSTRAINT fk_[your_table_name_here]_users FOREIGN KEY (user_id) REFERENCES users(user_id),

    -- Custom fields go here
    -- e.g., name VARCHAR(255) NOT NULL,
    -- e.g., is_active BOOLEAN DEFAULT TRUE NOT NULL,
    -- ...

    -- Audit Columns
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Generic - Add an index for Foreign Keys
-- CREATE INDEX idx_[your_table_name_here]_[fk_column] ON [your_table_name_here]([fk_column]);

-- Create an index on user_id
CREATE INDEX idx_[your_table_name_here]_user_id ON [your_table_name_here](user_id);