/*
    TABLE: franchises
    CHANGES: Add franchises table, add franchise_id to teams table
 */

CREATE TABLE franchises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    CONSTRAINT fk_franchises_organizations FOREIGN KEY (org_id) REFERENCES organizations(id),
    name VARCHAR(255) NOT NULL,
    acronym VARCHAR(8) NOT NULL,
    image_url VARCHAR(255),


    -- Audit Columns
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
CREATE INDEX idx_franchise_org_id ON franchises(org_id);

-- Make default franchise to backfill teams with
INSERT INTO franchises (org_id, name, acronym)
SELECT id, 'Unassigned', 'UA' FROM organizations;

-- Add franchise_id to teams
ALTER TABLE teams ADD COLUMN franchise_id BIGINT;

-- Backfill teams with the "Unassigned" franchise
UPDATE teams t
SET franchise_id = f.id
FROM franchises f
WHERE t.org_id = f.org_id
  AND f.acronym = 'UA';

-- Add not null and fkey
ALTER TABLE teams ALTER COLUMN franchise_id SET NOT NULL;
ALTER TABLE teams ADD CONSTRAINT fk_teams_franchise FOREIGN KEY (franchise_id) REFERENCES franchises(id);

-- Add index on franchise_id to teams
CREATE INDEX idx_teams_franchise_id ON teams(franchise_id);

-- Update teams.uq_teams_org_skill_name to include franchise_id
ALTER TABLE teams
    DROP CONSTRAINT IF EXISTS uq_teams_org_skill_name;

ALTER TABLE teams
    ADD CONSTRAINT uq_teams_org_franchise_skill_name
        UNIQUE (org_id, franchise_id, skill_group_id, name);