/*
    TABLE: skill_groups
    CHANGES: Adding the skill_groups table
 */

CREATE TABLE skill_groups (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      org_id BIGINT NOT NULL,
      CONSTRAINT fk_skill_groups_organizations FOREIGN KEY (org_id) REFERENCES organizations(id),
      name VARCHAR(255),
      acronym VARCHAR(255),
      colorHex VARCHAR(255),
      imageUrl VARCHAR(255),

      -- Audit Columns
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create an index on org_id
CREATE INDEX idx_skill_groups_org_id ON skill_groups(org_id);