/*
    TABLE: data_sources
    CHANGES: adding a data_sources table for storing data imports
 */

CREATE TABLE data_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    org_id BIGINT NOT NULL,
    CONSTRAINT fk_data_sources_organizations FOREIGN KEY (org_id) REFERENCES organizations(id),
    destination_table VARCHAR(255),
    url VARCHAR(255),
    data_format VARCHAR(255),
    comment VARCHAR(255),

    -- Audit Columns
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create an index on org_id
CREATE INDEX idx_data_sources_org_id ON data_sources(org_id);
