/*
    TABLE: players
    CHANGES: adding players table
 */

CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    CONSTRAINT fk_players_organizations FOREIGN KEY (org_id) REFERENCES organizations(id),
    skill_group_id BIGINT NOT NULL,
    CONSTRAINT fk_players_skill_groups FOREIGN KEY (skill_group_id) REFERENCES skill_groups(id),
    team_id BIGINT,
    CONSTRAINT fk_players_teams FOREIGN KEY (team_id) REFERENCES teams(id),
    user_id UUID NOT NULL,
    CONSTRAINT fk_players_users FOREIGN KEY (user_id) REFERENCES users(user_id),
    team_role VARCHAR(255),
    CONSTRAINT uq_players_team_role UNIQUE (team_id, team_role),

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create an index on user_id and team_id
CREATE INDEX idx_players_user_id ON players(user_id);
CREATE INDEX idx_players_team_id ON players(team_id);
