/*
    TABLE: teams
    CHANGES: adding teams table
 */

CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    CONSTRAINT fk_teams_organizations FOREIGN KEY (org_id) REFERENCES organizations(id),
    skill_group_id BIGINT NOT NULL,
    CONSTRAINT fk_teams_skill_groups FOREIGN KEY (skill_group_id) REFERENCES skill_groups(id),
    name VARCHAR(255),
    acronym VARCHAR(255),
    imageUrl VARCHAR(255),
    CONSTRAINT uq_teams_org_skill_name UNIQUE (org_id, skill_group_id, name),

    -- Audit Columns
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create an index on org_id
CREATE INDEX idx_teams_org_id ON teams(org_id);