name: Heroku Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Heroku Container Registry
      - name: Log in to Heroku Container Registry
        run: |
          echo "${{ secrets.HEROKU_AUTH_TOKEN }}" | docker login --username=_ --password-stdin registry.heroku.com

      # Build the Docker image
      - name: Build new Docker image
        run: docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

      # Push the Docker image to Heroku
      - name: Push new Docker image to Heroku
        run: docker push registry.heroku.com/$HEROKU_APP_NAME/web
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

      # Install Heroku CLI
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # Authenticate with Heroku using the Heroku API key (GitHub secret)
      - name: Login to Heroku
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN }}
          HEROKU_HEADERS: ${{ vars.HEROKU_HEADERS }}

#      # Set up the database
#      - name: Create harmony database user if absent
#        run: |
#            heroku pg:psql -a $HEROKU_APP_NAME <<EOF
#            DO $$
#            BEGIN
#              IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$JDBC_DATABASE_USERNAME') THEN
#                CREATE USER $JDBC_DATABASE_USERNAME WITH ENCRYPTED PASSWORD '$JDBC_DATABASE_PASSWORD';
#                GRANT ALL PRIVILEGES ON DATABASE $HEROKU_DB_NAME TO $JDBC_DATABASE_USERNAME;
#                GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $JDBC_DATABASE_USERNAME;
#                GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $JDBC_DATABASE_USERNAME;
#              END IF;
#            END $$;
#            EOF
#          env:
#            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#            HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
#            HEROKU_DB_NAME: ${{ secrets.HEROKU_DB_NAME }}
#            JDBC_DATABASE_USERNAME: ${{ secrets.JDBC_DATABASE_USERNAME }}
#            JDBC_DATABASE_PASSWORD: ${{ secrets.JDBC_DATABASE_PASSWORD }}
#
      # Set ENV vars in Heroku
#      - name: Set Heroku ENV Vars
#        run: heroku config:add FRONT_END_BASE_URL=$FRONT_END_BASE_URL JWT_SECRET=$JWT_SECRET JDBC_DATABASE_USERNAME=$JDBC_DATABASE_USERNAME JDBC_DATABASE_PASSWORD=$JDBC_DATABASE_PASSWORD DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET -a $HEROKU_APP_NAME
#        env:
#          FRONT_END_BASE_URL: ${{ vars.FRONT_END_BASE_URL }}
#          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
#          JWT_SECRET: ${{ secrets.JWT_SECRET }}
#          JDBC_DATABASE_USERNAME: ${{ secrets.JDBC_DATABASE_USERNAME }}
#          JDBC_DATABASE_PASSWORD: ${{ secrets.JDBC_DATABASE_PASSWORD }}
#          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
#          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}

      # Trigger Heroku deploy
      - name: Deploy the updated container on Heroku
        run: heroku container:release web -a $HEROKU_APP_NAME
          echo "Application successfully deployed to Heroku."
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN }}
