name: Heroku Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Heroku Container Registry
      - name: Log in to Heroku Container Registry
        run: |
          echo "${{ secrets.HEROKU_AUTH_TOKEN }}" | docker login --username=_ --password-stdin registry.heroku.com

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

      # Step 4: Push the Docker image to Heroku
      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/$HEROKU_APP_NAME/web
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

#      # Step 5: set up the database
#      - name: Create harmony database user if absent
#        run: |
#            DATABASE_NAME=${{ secrets.HEROKU_DB_NAME }}
#            DATABASE_USER=${{ secrets.DATABASE_USER }}
#            DATABASE_PASS=${{ secrets.DATABASE_PASS }}
#            heroku pg:psql -a ${{ secrets.HEROKU_APP_NAME }} <<EOF
#            DO $$
#            BEGIN
#              IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$DATABASE_USER') THEN
#                CREATE USER $DATABASE_USER WITH ENCRYPTED PASSWORD '$DATABASE_PASS';
#                GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USER;
#                GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DATABASE_USER;
#                GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $DATABASE_USER;
#              END IF;
#            END $$;
#            EOF
#          env:
#            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#

      # Step 5: Set ENV vars in Heroku
      - name: Set ENV Vars
        run: |
          heroku config:set FRONT_END_BASE_URL=$FRONT_END_BASE_URL --app $HEROKU_APP_NAME
          heroku config:set JWT_SECRET=$JWT_SECRET --app $HEROKU_APP_NAME
          heroku config:set DATABASE_USER=$DATABASE_USER --app $HEROKU_APP_NAME
          heroku config:set DATABASE_PASS=$DATABASE_PASS --app $HEROKU_APP_NAME
          heroku config:set DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID --app $HEROKU_APP_NAME
          heroku config:set DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}

      # Step 6: Trigger Heroku deploy
      - name: Deploy the app on Heroku
        run: heroku container:release web --app $HEROKU_APP_NAME
          echo "Application successfully deployed to Heroku."
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
