name: pr-checks.yml
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Run linter (ktfmt)
      - name: Run ktfmt
        run: ./gradlew ktfmtCheck

      # Step 4: Run tests
      - name: Run Tests
        run: ./gradlew clean test --continue -Dspring.profiles.active=test

      # Step 5: Display test results in github
      - name: Display Test Results in GitHub UI
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Test Results
          path: build/test-results/**/*.xml
          reporter: java-junit

      #Step 6: Upload gradle test report
      - name: Upload Gradle Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gradle-test-reports
          path: build/reports/tests/test/
          retention-days: 3